### ISSUE TITLE
Sans-serif generate local Helvetica

### ISSUE THREAD

**Issue by sylvainbaronnet** [jonathantneal/postcss-font-magician#10]
Why sans-serif generate @font-face aliasing sans-serif to local Helvetica ? 
And is there a way to disable this behaviour ?

Thank you

**Comment by rajdee** [comment]
It's because 'bootstrap' foundry used in default options.
```js
foundries: ['custom', 'hosted', 'bootstrap', 'google']
```
You can remove 'bootstrap' value from the 'foundries' option
```js
foundries: ['custom', 'hosted', 'google']
```

**Comment by sylvainbaronnet** [comment]
Thank you very much
