### ISSUE TITLE
Use PostCSS v5.x

### ISSUE THREAD

**Issue by MadLittleMods** [jonathantneal/postcss-font-magician#12]
Use [PostCSS](https://github.com/postcss/postcss) v5.x and the new API calls.

```
Container#eachAtRule is deprecated. Use Container#walkAtRules instead.
Container#eachDecl is deprecated. Use Container#walkDecls instead.
```

**Comment by Schweinepriester** [comment]
+1

**Comment by sylvainbaronnet** [comment]
+1

**Comment by lukelarsen** [comment]
+1

**Comment by lukelarsen** [comment]
It looks like this was already fixed with the only PR but for some reason when I install via npm what I get doesn't match the repo.

Did npm get updated with the latest PR?

**Comment by lukelarsen** [comment]
@jonathantneal - Any ideas on this?

**Comment by Galvo87** [comment]
@jonathantneal same issue here, installing via npm results in a version using postcss v4 instead of v5.

**Comment by jonathantneal** [comment]
Ah, the version wasn’t bumped with the API change. I will get to this tonight!

**Comment by jonathantneal** [comment]
Resolved by https://github.com/jonathantneal/postcss-font-magician/commit/8ffe04bab52215c812044365f64b699c89a06d62 and published to npm!
