### ISSUE TITLE
Container#eachAtRule is deprecated. 

### ISSUE THREAD

**Issue by neonick** [jonathantneal/postcss-font-magician#13]
Hi! I use a last versions of PostCSS and plugins, but when I add font-magican I saw this in my command line:
```
Container#eachAtRule is deprecated. Use Container#walkAtRules instead.
Container#eachDecl is deprecated. Use Container#walkDecls instead.
```
How can I fix it?

**Comment by TrySound** [comment]
@neonick It's just deprecating that this plugin uses old postcss version. But it won't make impact  on build process. Just ignore it.

**Comment by neonick** [comment]
ping @jonathantneal :)

**Comment by jonathantneal** [comment]
Resolved by https://github.com/jonathantneal/postcss-font-magician/commit/8ffe04bab52215c812044365f64b699c89a06d62 and published to npm!
