### ISSUE TITLE
Is there a way to only load only certain font variants?

### ISSUE THREAD

**Issue by jrambeck** [jonathantneal/postcss-font-magician#14]
A Google Font like Open Sans has 11 variants. Is there a way to specify specific variants only?

Open Sans example:
- Normal 300
- Italic 300
- Normal 700

**Comment by andrelima** [comment]
Needing this feature as well... :+1:

**Comment by rajdee** [comment]
You can use a [variant option](https://github.com/rajdee/postcss-font-magician#varaints) in my [fork](https://github.com/rajdee/postcss-font-magician)

**Comment by sylvainbaronnet** [comment]
@rajdee Is it possible to merge the variants option in the main repo ?

**Comment by andrelima** [comment]
@rajdee @sylvainbaronnet Yes, would love for this to get in...

**Comment by AdamQuadmon** [comment]
Hummm, I think this project is dead :(

**Comment by rajdee** [comment]
Hi @jrambeck @andrelima @sylvainbaronnet @AdamQuadmon
You can use the [variants option](https://github.com/jonathantneal/postcss-font-magician#variants) since version 1.5.0
