### ISSUE TITLE
Unexpected results when trying to use the 'hosted' option

### ISSUE THREAD

**Issue by alibby251** [jonathantneal/postcss-font-magician#18]
I've been trying out your plugin in PostCSS, but am getting some very odd / unexpected results, and need some help please!

My gulpfile.js file looks like this:

```
var gulp = require('gulp');
var postcss = require('gulp-postcss');

var definitions = ({
    hosted: '/fonts'      // The CSS output stylesheet is in a folder called dest, at the same level
});

gulp.task('default', ['css']);

gulp.task('css', function () {
  return gulp.src('src/*.css').pipe(
     postcss([
        require('postcss-font-magician')(definitions)
     ])
  ).pipe(
     gulp.dest('dest/')
  );
});
```

In my package.json file, I have this:

```
  "dependencies": {
    "postcss": "^5.0.8"
  },
  "devDependencies": {
    "autoprefixer": "^6.0.3",
    "gulp": "^3.9.0",
    "gulp-postcss": "^6.0.0",
    "gulp-webpcss": "^1.1.0",
    "postcss-font-magician": "^1.3.0"
  }
}
```

The folder structure looks like this:

![screenshot](https://cloud.githubusercontent.com/assets/802739/11446643/bec460b4-9531-11e5-8fcc-5928d24a2a05.png)

I particularly need to use the local hosted option, but no matter what happens, I either get nothing appear in my compiled file, or I get Google Fonts used instead. To try to understand what is going on, I've documented what I've found so far:
1. Using "hosted" option above doesn't reference fonts folder, but Google Fonts instead - font in use is Roboto, which is available on Google Fonts, even though I have it available locally. 
2. If I replace the `defintions` object with this:

```
/*var definitions = ({
    hosted: 'google'
});
```

...it gives the same result as above - Google Fonts is used, not the local. In theory this should throw an error, as 'google' isn't a valid option for this attribute?
1. Using this in the `definitions` object (as suggested on #1) doesn't work for me either - it's still referencing Google Fonts, even though it should reference the local version.
2. I've tried renaming the locally stored fonts to see if length or hyphens were causing an issue - the original names had two hyphens in them, but this has had no effect. 
3. When compiling the code, the results do appear but the `src` line could use some improvement in formatting; it doesn't look as neat as your documentation ;-)

It seems that no matter what happens, Google Fonts is being called, and that the local host option is either ignored or being overwritten by Google Fonts. I've had a look at the code and as far as I can see, it looks like Google Fonts is being set as a default - as far as I can see, it isn't enough to simply call "hosted: XXXX"? 

I can use the custom: option suggested in one of the issues logged - this does work, but weighs in at 14 lines to simply set one font option, and not even all of the font formats! This kinda destroys the whole point of using the plugin - I think the idea is perfect, but I would rather simply set the @font-face manually, as it is less code. I would definitely second the need to not drop in all of the different font types - this will likely add a lot of unnecessary extra CSS to the style sheet, when only 1 font weight/type may be required.

Any ideas on where to go from here?

**Comment by Danilux** [comment]
Having the same issue documented here.

**Comment by srahulprdxn** [comment]
I am facing the same issue. Hosted option is not working.

**Comment by brettdewoody** [comment]
Same issue. Google fonts work fine. Using the 'hosted' option causes 404 errors for the font URLs.

**Comment by cmnstmntmn** [comment]
any update on this issue ?

**Comment by rajdee** [comment]
Hi @alibby251 @cmnstmntmn!
I fixed the issue with `hosted` option. In your case you should use this option:
```js
  hosted: ['./fonts']
```
or 
```js
  hosted: ['./fonts', 'custom/font/path/on/site']
```
