### ISSUE TITLE
Any plan to support `unicode-range`?

### ISSUE THREAD

**Issue by cayter** [jonathantneal/postcss-font-magician#19]
As topic. The example CSS is [here](https://fonts.googleapis.com/css?family=Kanit:400,700&subset=thai,latin,vietnamese,latin-ext).

**Comment by rajdee** [comment]
@cayter You can use `unicode-range` param in this [fork](https://github.com/rajdee/postcss-font-magician#unicode-range)

**Comment by rajdee** [comment]
@cayter You can use the [unicode-range](https://github.com/jonathantneal/postcss-font-magician#unicode-range) param since version 1.5.0

**Comment by cayter** [comment]
Oh ok thanks man!
