### ISSUE TITLE
Option to force https urls

### ISSUE THREAD

**Issue by joewalnes** [jonathantneal/postcss-font-magician#23]
Currently the generated `@font-face` URL is protocol relative (e.g. `url(//fonts.gstatic.com/...)`)

I would like to be able to force it to always use `https://`, because:

* Sometimes sites will be served unencrypted on a local network (e.g. http://localhost) but I always want external traffic to be encrypted
* Allows the fonts to work in pages accessed locally using `file://` scheme
* HTTPS is generally considered better practice than protocol relative: http://www.paulirish.com/2010/the-protocol-relative-url/

**Comment by rajdee** [comment]
@joewalnes You can use the [protocol](https://github.com/jonathantneal/postcss-font-magician#protocol) option since version 1.5.0. I think that it can solve your problem.
