### ISSUE TITLE
Problem when I use font magician with webpack

### ISSUE THREAD

**Issue by Xhamps** [jonathantneal/postcss-font-magician#29]
Now i'm working in a project. I had to add this the plugin in the webpack.
But didn't work fine. The font not render correctly.
I start debug and I saw in code, that remove the protocol of url font in [this line](https://github.com/jonathantneal/postcss-font-magician/blob/master/index.js#L160).
I tried comment this line in plugin and build again. In this moment i don't have a mistake.

It there a way to fix this?

**Comment by devlato** [comment]
+1 maybe possible to pass some option to build urls with protocol?

**Comment by devlato** [comment]
@jonathantneal Are you alive? The repo haven't been updated since last December

**Comment by devlato** [comment]
@jonathantneal also there is a pull request of @spicydonuts that is fixing the issue: https://github.com/jonathantneal/postcss-font-magician/pull/26

**Comment by rajdee** [comment]
@Xhamps @devlato 
You can use the [protocol](https://github.com/jonathantneal/postcss-font-magician#protocol) option since version 1.5.0.
