### ISSUE TITLE
 there is a small error in the version 1.5.0

### ISSUE THREAD

**Issue by DUBANGARCIA** [jonathantneal/postcss-font-magician#32]
there is a semicolon must be deleted in the line 324

![image](https://cloud.githubusercontent.com/assets/17387158/19542233/1ef8e872-9632-11e6-8d6d-2fb1c1b1ab6d.png)

![image](https://cloud.githubusercontent.com/assets/17387158/19542239/2f137448-9632-11e6-9574-23a8754c7a4d.png)

**Comment by rajdee** [comment]
It was fixed. Thank you!
