### ISSUE TITLE
Parameters for Google Fonts

### ISSUE THREAD

**Issue by Aylay** [jonathantneal/postcss-font-magician#38]
Hi,

Is it possible to create a parameter like `font-family: "Roboto" 700;` to import just the Roboto font with `font-weight: 700;` in Google ?

I just want to reduce the final css file.

Tks

**Comment by rajdee** [comment]
Hi @Aylay
Yes, you should use this option:
```js
require('postcss-font-magician')({
   variants: {
                'Roboto': {
                    '700': []
                }
            }
});
```
or if you can support modern browsers (IE9+, AB4.4+, IOS 5.1+)
```js
require('postcss-font-magician')({
   variants: {
                'Roboto': {
                    '700': ['woff', 'woff2']
                }
            }
});
```

**Comment by ranosi** [comment]
I'm trying to use this parameter but it's not working for me. I try to import only Roboto 700 and it's bring me all formats.
What can i do to fix this? I test usign this same example above.

**Comment by rajdee** [comment]
Hi, ranosi!
Can you give more information? 

- what version of the postcss-font-magician are you using? 
- what build system are your using?
- can you show the options

**Comment by ranosi** [comment]
@rajdee i manange to work now when i deleted de line that saves de font local. I don't know why this happen.
I'm using the version 1.6.1 with gulp.

**Comment by rajdee** [comment]
I close this problem, if necessary it can be opened again
