### ISSUE TITLE
'hosted' option issue

### ISSUE THREAD

**Issue by ukaric** [jonathantneal/postcss-font-magician#39]
Hi, I have problem with `hosted` option when i try to include non google fonts, mind that google fonts work just fine as you can see [here](http://scrawny-trains.surge.sh/). As noted somewhere it only works via `http` or `https` call or localserver which is normal behavior. 

But my problem lies in fact that plugin does pick up costume fonts but does not seems to load them properly. Here is my directory tree :

```
├───.tmp
│   └───fonts
├───assets
│   ├───fonts
│   ├───images
│   ├───js
│   ├───styles
│   └───templates
└───gulp
    └───tasks
```
You can safely ignore `/assets` because i'm in process of testing stuff. Everything is served and viewed from `/.tmp` folder.

Or if it is easier I made some screen shoots for better visualization.

![2017-01-19](https://cloud.githubusercontent.com/assets/9012882/22103009/c6a0219a-de39-11e6-87b4-8fea6e1b3266.png)

Now for the main part `index.html` viewed locally.

![2017-01-19 1](https://cloud.githubusercontent.com/assets/9012882/22103128/3be63fb6-de3a-11e6-8c80-9fc96bbce62a.png)

I have installed first font locally and it does pick it up as seen but with the one that I did not install it reverts to default one. Here is the hosted version of the same page, you can check it out [here](http://spiffy-vegetable.surge.sh/).

Part of gulp task 

```
let preProcessors = [
  postcssImport,
  precss,
  fontMagician({
    hosted: ['./.tmp/fonts']
  }),
  cssMqpacker,
  willChange,
  colorRgbaFallback,
  opacity,
  pseudoelements,
  vmin,
  pixrem,
  autoprefixer
];

let postProcessors = [ cssnano ];

let isProduction = args.env === "production";

gulp.task("styles", () => {
  gulp
    .src("./assets/styles/**/*.css")
    .pipe(postcss(preProcessors))
    .pipe(gulpif(isProduction, postcss(postProcessors)))
    .pipe(gulp.dest("./.tmp"));
});
```
Any help would be appreciated because I'm really bashing head over this one I know its not that big of a deal but this has to be pure class plugin and i really want to incorporate it. 

Thanks in advance :v:

**Comment by rajdee** [comment]
Hi @kadza93 
If you have problems with relative paths you can always use the second params of hosted option. You can try to use this option for your case:
```
hosted: ['./.tmp/fonts', './fonts/']
```
