### ISSUE TITLE
Attempting to set Foundaries throws: 'options.foundries.unshift is not a function'

### ISSUE THREAD

**Issue by tohuw** [jonathantneal/postcss-font-magician#51]
Using v2.0.0 via Gulp:

    gulp.task('css', function () {
        var sourcemaps = require('gulp-sourcemaps');
        var postcss    = require('gulp-postcss');

        return gulp.src('./input/*.css')
        .pipe( sourcemaps.init() )
        .pipe( postcss([
            hosted: ['./foo/bar/baz'],
            foundries: 'hosted, custom',
        ]) )
        .pipe( sourcemaps.write('.') )
        .pipe( gulp.dest('./dest') );
    }),

Throws:

	events.js:182
	      throw er; // Unhandled 'error' event
	      ^
	TypeError: options.foundries.unshift is not a function
	    at /Users/rscottadams/Projects/tohuwnet/node_modules/postcss-font-magician/index.js:336:31
	    at LazyResult.run (/Users/rscottadams/Projects/tohuwnet/node_modules/postcss/lib/lazy-result.js:270:20)
	    at LazyResult.asyncTick (/Users/rscottadams/Projects/tohuwnet/node_modules/postcss/lib/lazy-result.js:185:32)
	    at /Users/rscottadams/Projects/tohuwnet/node_modules/postcss/lib/lazy-result.js:190:27
	    at <anonymous>
	    at process._tickCallback (internal/process/next_tick.js:188:7)

Omitting the `foundaries` option fixes the error.

Am I misusing the option, or is this a bug?

**Comment by rajdee** [comment]
Hi @tohuw 
The `foundries` option should be an array. I need to add validation and conversation to an array in a future version if the parameter is specified by a string.

**Comment by tohuw** [comment]
Ah I see that now. Might be best to call that out in the README to avoid confusion, at least until you add a handler to convert the value. I'll submit a simple PR for that. Thanks for the help!
