### ISSUE TITLE
Protocol-relative URLs fail on local

### ISSUE THREAD

**Issue by jhpratt** [jonathantneal/postcss-font-magician#53]
Everything Google serves is over HTTPs, so why not include that by default? I just ran across this on local, as the protocol naturally isn't HTTP(S).

**Comment by jhpratt** [comment]
Looks like it's [this line](https://github.com/jonathantneal/postcss-font-magician/blob/master/index.js#L26) that sets the protocol (or lack thereof).

**Comment by rajdee** [comment]
Hi @jhpratt 
Because this plugin is used not only for Google fonts. You can use [protocol](https://github.com/jonathantneal/postcss-font-magician#protocol) option in the plugin config
