### ISSUE TITLE
Convert local font files

### ISSUE THREAD

**Issue by strarsis** [jonathantneal/postcss-font-magician#55]
Does this plugin also convert local font files (TTF -> WOFF/WOFF2)?
How could I integrate TTF to web font format conversion into my existing webpack workflow?

**Comment by rajdee** [comment]
Hi, @strarsis 
Nope, this plugin doesn't convert local files because it has other purposes. You can find the WOFF/WOFF2 versions of your font or convert using online converters

**Comment by strarsis** [comment]
@rajdee: How could I integrate TTF->WOFF/WOFF2 conversion into my webpack/postcss based workflow?
How are you handling font file conversions, subsetting?

**Comment by rajdee** [comment]
@strarsis Why do you want to convert fonts via webpack? This is a one-time operation and for this you can use online services i.e. Font Squirrel, etc

**Comment by strarsis** [comment]
@rajdee: I would be able to modify some conversion/minification options without relying on an external service.

**Comment by rajdee** [comment]
Sorry, but I don't know the appropriate webpack loader for converting fonts because this isn't a webpack task

**Comment by rajdee** [comment]
I'm closing this issue because this doesn't apply to the PFM
