### ISSUE TITLE
Doesn't detect font-weight or font-style

### ISSUE THREAD

**Issue by simonlc** [jonathantneal/postcss-font-magician#6]
When choosing a font available in multiple weights or styles, instead of only embedding which font you're using, the plugin embeds every variation of that font.

For example, Open Sans has 10 variations, it will declare them all, while I may only want to use one. This can be easily tested in the live interpreter: http://jonathantneal.github.io/postcss-font-magician/

**Comment by andyjansson** [comment]
Unfortunately it's hard to know what font variant you are using due to the cascade. I'm not sure we can do anything about it without bringing the DOM into the mix.

**Comment by jonathantneal** [comment]
The good news is that `@font-face` rules’ sources are not downloaded until they are used, so we’re talking about an issues of bytes versus kilobytes.

That being said, you can configure font magician to load only specific weights and styles.

**Comment by simonlc** [comment]
Thanks @andyjansson and @jonathantneal I thought that might be the case when watching the network tab.
I guess I didn't think it through, I thought you could still kind of see which weights you're using, but you'd run into issues pretty fast without the cascade. This might be something for UnCSS instead, though that project doesn't seem to be very active.
