### ISSUE TITLE
using with webpack for vuejs 2.0

### ISSUE THREAD

**Issue by alpody** [jonathantneal/postcss-font-magician#60]
I am a beginner in vue js. I want use postcss-font-magician in webpack 

I use next .postcssrc.js for configuring postcss-modules.

module.exports = {
    options: {
    parser: require('postcss-scss')
    },
    "plugins": {
      // to edit target browsers: use "browserslist" field in package.json
      "postcss-import": {},
      //"autoprefixer": {},
     "postcss-font-magician": {
         foundries: ['google']
     },
     'postcss-cssnext': {},
    'precss': {},
       'css-mqpacker': {},
    'cssnano': {autoprefixer:false},
    }
  };

Example with font-family not working inside *.vue files
body {
   font-family: "Alice";
}

**Comment by rajdee** [comment]
Hi @alpody 
Please show the webpack rule where you are configuring the postcss-loader
