### ISSUE TITLE
"'charCodeAt' is not defined" error with non-string font names

### ISSUE THREAD

**Issue by JayBauer** [jonathantneal/postcss-font-magician#61]
If I have a rule such as `font-family: sans-serif;`, I'm getting the error `Cannot read property 'charCodeAt' of undefined` in my console. However, `font-family: "Source Sans Pro", sans-serif;` gives me no trouble. Seems to be only when there's no string available that the issue occurs.

I have confirmed this is `font-magician`'s doing, and have confirmed that it happens regardless of my PostCSS plugin load order, even when `font-magician` is the only plugin being used.

This wouldn't be a huge issue for a typical user-generated CSS sheet, but certain libraries such as [normalize.css](https://necolas.github.io/normalize.css/) have a lot of these types of rules for resets. Is there a known fix for this problem?

**Comment by timkelty** [comment]
Having the same issue, in my case with `font-family: 'Open Sans'`

**Comment by jhpratt** [comment]
@jonathantneal Confirming with `font-family: 'Roboto Mono'`, using single or double quotes. The actual font name does not seem to matter, just that it's quoted.

**Comment by rajdee** [comment]
@JayBauer @timkelty @jhpratt 
I can't reproduce these issues. The `pfm` works with `font-family: sans-serif` or `font-family: 'Open Sans` as expected. Please provide more information about `Postcss` and `PFM` versions and postcss settings
