### ISSUE TITLE
Importing fonts with a space in the name 

### ISSUE THREAD

**Issue by adrice727** [jonathantneal/postcss-font-magician#63]
I found that I'm unable to import Google Fonts that contain a space in the name.  My `postcss` config:
```js
module.exports = {
  plugins: {
    'postcss-import': {},
    'postcss-mixins': {},
    'postcss-simple-vars': {},
    'autoprefixer': {},
    'postcss-assets': {
      basePath: './src',
      loadPaths: ['**']
    },
    'postcss-nested': {},
    'stylelint': {},
    'precss': {},
    'postcss-font-magician': {
      foundries: ['google'],
      variants: {
        'Raleway': {
          '300': [],
          '400': [],
          '700': []
        },
        'Nunito': {
          '200': [],
          '300': [],
          '400': [],
          '700': []
        },
        'Gamja Flower': {
          '400': [],
        }
      },
    }
  }
}
```

`Raleway` and `Nunito` load fine, but not `Gamja Flower`.  I've also tried using `Gamja+Flower` in the `config`, and using the `font-family` both with and without the `+` to no avail.  It doesn't seem to be specific to this font either.

**Comment by adrice727** [comment]
I resolved this issue by using a `-`, so that my config looks like:
```
        'Gamja-Flower': {
          '400': [],
        }
```
Is it possible that this is something specific to `webpack 4`?  Either way, I'm happy to make a PR to update the `README`.

**Comment by rajdee** [comment]
Hi @adrice727 
The `Gamja Flower` won't work anyway because it doesn't exist in [google-fonts-complete](https://raw.githubusercontent.com/jonathantneal/google-fonts-complete/master/google-fonts.json) which is used in PFM. I need to update `google-fonts-complete` with the latest google fonts

**Comment by rajdee** [comment]
@adrice727 I updated the `google-fonts-complete` and this issue should be fixed
