### ISSUE TITLE
Incorrect parse not array options

### ISSUE THREAD

**Issue by kuflash** [jonathantneal/postcss-font-magician#64]
Hi! An error was found when using a plugin in the pipeline of other plug-ins. In particular, the problem arose with [cssnano](https://github.com/ben-eb/cssnano). Here is the [issue](https://github.com/ben-eb/cssnano/issues/420) with description this problem. 

I tried to fix it and send you PR for resolve this problem.

**Comment by kuflash** [comment]
@rajdee tell me please, when do you plan the next release, so that the fix of this will be included in it?

**Comment by rajdee** [comment]
@kuflash I'm planning to release a new version with this fix today

**Comment by kuflash** [comment]
@rajdee great thank you!
