### ISSUE TITLE
Problem with PostCSS and font-magician versions

### ISSUE THREAD

**Issue by Juli4nAc0sta** [jonathantneal/postcss-font-magician#74]
Hello,

I have a problem apparently with the PostCSS and font-magician versions.

The error is as follows 

` ERROR  Unknown error from PostCSS plugin. Your current PostCSS version is 7.0.14, but postcss-font-magician uses 6.0.23. Perhaps this is the source of the error below.
`

**Comment by rajdee** [comment]
@Juli4nAc0sta Please use the latest version of the plugin
