### ISSUE TITLE
Font Display

### ISSUE THREAD

**Issue by iantearle** [jonathantneal/postcss-font-magician#76]
Google have now implemented the css property font-display - it would be good to utilise this when using font-magician

**Comment by rajdee** [comment]
Hi @iantearle 
It was added in version [1.5.0](https://github.com/jonathantneal/postcss-font-magician/blob/master/CHANGELOG.md#150-2016-10-11) 3 years ago :)
This is supported as a [global](https://github.com/jonathantneal/postcss-font-magician#font-display) parameter, but I am planning to support as a custom font parameter

**Comment by iantearle** [comment]
Completely missed that. thanks.
