### ISSUE TITLE
Generated nodes not contain source property

### ISSUE THREAD

**Issue by OEvgeny** [jonathantneal/postcss-font-magician#9]
I'm really not sure that it's an issue or may be question. For some reason it causes other plugins to fail.
The problem is that generated by your plugin nodes not contain ``source`` property unlike the other.
It can be proven by simple snippet:
```
require('postcss')([require('postcss-font-magician')()])
  .process('body {font-family:Oxygen}', {from: 'myfile.css'})
  .then(function(res) {
     console.log(res.root.nodes[0].source)
  })
```

**Comment by andyjansson** [comment]
If we were to add a source, the question is what the source should be. A `font*` declaration? What if you have multiple declarations referencing the same font?

**Comment by OEvgeny** [comment]
Can't reproduce now. Closing.
