### ISSUE TITLE
Support for postcss 8 ?

### ISSUE THREAD

**Issue by anikethsaha** [jonathantneal/postcss-font-magician#91]
Hi, we are using this plugin in cssnano as a dev dependency for testing [here](https://github.com/cssnano/cssnano/blob/master/packages/postcss-minify-selectors/src/__tests__/index.js#L2)

As we are implementing support for postcss 8  in cssnano https://github.com/cssnano/cssnano/pull/954. It would be great if this plugin can be migrated as well to postcss 8. Postcss does supports old plugins to run in `8` but still, there would be deprecation warning and they would remove the support in the future. 

I can submit a PR given if you can review/release it. Else I will probably just copy-paste the code as a dummy plugin as we are only using it for testing.

Let me know whichever is best for you as this is non-blocker support so either way works for me, just wanted to know if this is in consideration. 

And thanks for the plugin.

**Comment by rajdee** [comment]
@anikethsaha Postcss 8.x was supported in [v3.0.0](https://github.com/jonathantneal/postcss-font-magician/releases/tag/v3.0.0)

**Comment by anikethsaha** [comment]
Thanks
